### ISSUE TITLE
cache does not save on error

### ISSUE THREAD

**Issue by tily** [tily/barthes#6]
runner does not save cache on error, typically interruption with Ctrl-C.

**Comment by tily** [comment]
```
$ ruby bin/barthes -e example/q3_env.json example/interrupt_spec.json
Q3
        Interrupt
                #1 one action
                        request:
                                {
                                  "Action": "CreateQueue",
                                  "QueueName": "before"
                                }
                        response:
                                {
                                  "CreateQueueResponse": {
                                    "CreateQueueResult": {
                                      "QueueUrl": "http://q3-global.herokuapp.com/*/before"
                                    },
                                    "ResponseMetadata": {
                                      "RequestId": "951f0777-918d-4a2e-9f2a-dbe2997e8491"
                                    }
                                  }
                                }
                        result: success
                #2 another action
^C/root/dev/barthes/lib/barthes/action.rb:39:in `sleep': Interrupt
        from /root/dev/barthes/lib/barthes/action.rb:39:in `action'
        from /root/dev/barthes/lib/barthes/runner.rb:113:in `block in handle_action'
        from /root/dev/barthes/lib/barthes/reporter.rb:32:in `report'
        from /root/dev/barthes/lib/barthes/runner.rb:111:in `handle_action'
        from /root/dev/barthes/lib/barthes/runner.rb:89:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:93:in `block in walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:92:in `each'
        from /root/dev/barthes/lib/barthes/runner.rb:92:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:84:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:93:in `block in walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:92:in `each'
        from /root/dev/barthes/lib/barthes/runner.rb:92:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:59:in `block (3 levels) in run'
        from /root/dev/barthes/lib/barthes/reporter.rb:32:in `report'
        from /root/dev/barthes/lib/barthes/runner.rb:58:in `block (2 levels) in run'
        from /root/dev/barthes/lib/barthes/runner.rb:56:in `each'
        from /root/dev/barthes/lib/barthes/runner.rb:56:in `block in run'
        from /root/dev/barthes/lib/barthes/reporter.rb:32:in `report'
        from /root/dev/barthes/lib/barthes/runner.rb:54:in `run'
        from /root/dev/barthes/lib/barthes/cli.rb:28:in `start'
        from bin/barthes:4:in `<main>'

[root@devopsapl001 barthes]# ls barthes-cache.json
ls: cannot access barthes-cache.json: そのようなファイルやディレクトリはありません
```

**Comment by tily** [comment]
```
$ ruby bin/barthes -e example/q3_env.json example/interrupt_spec.json
Q3
        Interrupt
                #1 one action
                        request:
                                {
                                  "Action": "CreateQueue",
                                  "QueueName": "before"
                                }
                        response:
                                {
                                  "CreateQueueResponse": {
                                    "CreateQueueResult": {
                                      "QueueUrl": "http://q3-global.herokuapp.com/*/before"
                                    },
                                    "ResponseMetadata": {
                                      "RequestId": "e848aa26-4576-4ee1-b851-6e41ee7e78ba"
                                    }
                                  }
                                }
                        result: success
                #2 another action
^C/root/dev/barthes/lib/barthes/action.rb:39:in `sleep': Interrupt
        from /root/dev/barthes/lib/barthes/action.rb:39:in `action'
        from /root/dev/barthes/lib/barthes/runner.rb:118:in `block in handle_action'
        from /root/dev/barthes/lib/barthes/reporter.rb:32:in `report'
        from /root/dev/barthes/lib/barthes/runner.rb:116:in `handle_action'
        from /root/dev/barthes/lib/barthes/runner.rb:94:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:98:in `block in walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:97:in `each'
        from /root/dev/barthes/lib/barthes/runner.rb:97:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:89:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:98:in `block in walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:97:in `each'
        from /root/dev/barthes/lib/barthes/runner.rb:97:in `walk_json'
        from /root/dev/barthes/lib/barthes/runner.rb:60:in `block (3 levels) in run'
        from /root/dev/barthes/lib/barthes/reporter.rb:32:in `report'
        from /root/dev/barthes/lib/barthes/runner.rb:59:in `block (2 levels) in run'
        from /root/dev/barthes/lib/barthes/runner.rb:57:in `each'
        from /root/dev/barthes/lib/barthes/runner.rb:57:in `block in run'
        from /root/dev/barthes/lib/barthes/reporter.rb:32:in `report'
        from /root/dev/barthes/lib/barthes/runner.rb:55:in `run'
        from /root/dev/barthes/lib/barthes/cli.rb:28:in `start'
        from bin/barthes:4:in `<main>'

$ cat barthes-cache.json
{
  "test": "\n  \n    http://q3-global.herokuapp.com/*/before\n  \n  \n    e848aa26-4576-4ee1-b851-6e41ee7e78ba\n  \n\n    http://q3-global.herokuapp.com/*/before\n  http://q3-global.herokuapp.com/*/before\n    e848aa26-4576-4ee1-b851-6e41ee7e78ba\n  e848aa26-4576-4ee1-b851-6e41ee7e78ba"
}
```
